CREATE TABLE [dbo].[ods_oib_marketing_campaign_out] (
    [Member First Name]    NVARCHAR (255) NULL,
    [Member Surname]       NVARCHAR (255) NULL,
    [TradingName]          NVARCHAR (255) NULL,
    [Address]              NVARCHAR (255) NULL,
    [Suburb]               NVARCHAR (255) NULL,
    [State]                NVARCHAR (255) NULL,
    [Postcode]             NVARCHAR (255) NULL,
    [PostalAddress]        NVARCHAR (255) NULL,
    [PostalSuburb]         NVARCHAR (255) NULL,
    [PostalState]          NVARCHAR (255) NULL,
    [PostalPostcode]       NVARCHAR (255) NULL,
    [Phone]                NVARCHAR (255) NULL,
    [AfterHoursPhone]      NVARCHAR (255) NULL,
    [Fax]                  NVARCHAR (255) NULL,
    [Mobile]               NVARCHAR (255) NULL,
    [Email]                NVARCHAR (255) NULL,
    [F1]                   NVARCHAR (255) NULL,
    [f2]                   NVARCHAR (255) NULL,
    [f3]                   NVARCHAR (255) NULL,
    [f4]                   NVARCHAR (255) NULL,
    [f5]                   NVARCHAR (255) NULL,
    [f6]                   FLOAT (53)     NULL,
    [f7]                   NVARCHAR (255) NULL,
    [comment]              VARCHAR (255)  NULL,
    [pure_address]         VARCHAR (255)  NULL,
    [pure_PostalAddress]   VARCHAR (255)  NULL,
    [IbaisClientCode]      VARCHAR (50)   NULL,
    [IbaisClientExecutive] VARCHAR (50)   NULL,
    [IbaisClientName]      VARCHAR (255)  NULL,
    [IbaisAddress]         VARCHAR (255)  NULL,
    [IbaisPostalAddress]   VARCHAR (255)  NULL,
    [IbaisPostcode]        VARCHAR (10)   NULL,
    [IbaisPhoneno]         VARCHAR (50)   NULL,
    [Ibaisfax]             VARCHAR (50)   NULL,
    [Ibaismobile]          VARCHAR (50)   NULL,
    [Ibaisemail]           VARCHAR (50)   NULL
);

