CREATE TABLE [dbo].[ods_oib_marketing_campaign1] (
    [m_FIELDf1] VARCHAR (500) NULL,
    [m_FIELDf2] VARCHAR (500) NULL,
    [m_FIELD2]  VARCHAR (500) NULL,
    [m_FIELD3]  VARCHAR (500) NULL,
    [m_FIELD4]  VARCHAR (500) NULL,
    [m_FIELD5]  VARCHAR (500) NULL,
    [m_FIELD6]  VARCHAR (500) NULL,
    [m_FIELD7]  VARCHAR (500) NULL,
    [m_FIELD8]  VARCHAR (500) NULL
);

