CREATE TABLE [dbo].[parmia_dds_fct_client] (
    [SystemCode]                   VARCHAR (20)    NOT NULL,
    [BranchCode]                   VARCHAR (50)    NOT NULL,
    [Local_BranchCode]             VARCHAR (20)    NOT NULL,
    [ClientCode]                   VARCHAR (255)   NOT NULL,
    [ClientName]                   VARCHAR (255)   NULL,
    [Address_Line_1]               VARCHAR (255)   NULL,
    [Address_Line_2]               VARCHAR (255)   NULL,
    [Address_Line_3]               VARCHAR (255)   NULL,
    [Suburb]                       VARCHAR (255)   NULL,
    [Postcode]                     VARCHAR (255)   NULL,
    [Postal_Address_Line_1]        VARCHAR (255)   NULL,
    [Postal_Address_Line_2]        VARCHAR (255)   NULL,
    [Postal_Address_Line_3]        VARCHAR (255)   NULL,
    [Postal_Suburb]                VARCHAR (255)   NULL,
    [Addressee]                    VARCHAR (255)   NULL,
    [Salutation]                   VARCHAR (255)   NULL,
    [Gender]                       VARCHAR (30)    NULL,
    [ClientExecutiveCode]          VARCHAR (50)    NULL,
    [TeamCode]                     VARCHAR (100)   NULL,
    [Phone]                        VARCHAR (255)   NULL,
    [Fax]                          VARCHAR (255)   NULL,
    [Mobile]                       VARCHAR (255)   NULL,
    [Subagent]                     VARCHAR (255)   NULL,
    [Email]                        VARCHAR (255)   NULL,
    [ABN]                          VARCHAR (255)   NULL,
    [Retail_Wholesale]             VARCHAR (255)   NULL,
    [Contact_Method]               VARCHAR (255)   NULL,
    [Contact_Preference]           VARCHAR (255)   NULL,
    [Contact_Comments]             VARCHAR (255)   NULL,
    [NoOfEmployee]                 INT             NULL,
    [Process_Key]                  INT             NOT NULL,
    [Operation]                    VARCHAR (255)   NULL,
    [Mailing_Contact]              VARCHAR (255)   NULL,
    [Commence_Date]                SMALLDATETIME   NULL,
    [Association_Code]             VARCHAR (100)   NULL,
    [Legacy_COBR]                  VARCHAR (100)   NULL,
    [Anzsic_Code]                  VARCHAR (100)   NULL,
    [Team]                         VARCHAR (100)   NULL,
    [Home_Phone]                   VARCHAR (255)   NULL,
    [Ledger_Code]                  VARCHAR (100)   NULL,
    [Debtor_Code]                  VARCHAR (100)   NULL,
    [Introduced_By]                VARCHAR (255)   NULL,
    [AlternateClientExecutiveCode] VARCHAR (50)    NULL,
    [Division]                     VARCHAR (50)    NULL,
    [Incomeband_past12mts]         VARCHAR (30)    NULL,
    [Incomeband_lfy]               VARCHAR (30)    NULL,
    [Currency]                     VARCHAR (50)    NULL,
    [Other_Currency]               VARCHAR (50)    NULL,
    [Terms]                        VARCHAR (255)   NULL,
    [Statement]                    VARCHAR (255)   NULL,
    [Broker]                       VARCHAR (100)   NULL,
    [DOB]                          VARCHAR (50)    NULL,
    [Authorised_Rep]               VARCHAR (255)   NULL,
    [Opt_Out_Date]                 VARCHAR (255)   NULL,
    [Opt_Out_Method]               VARCHAR (20)    NULL,
    [VIP]                          VARCHAR (255)   NULL,
    [ActiveClientInd]              VARCHAR (1)     NULL,
    [BADeletedDate]                SMALLDATETIME   NULL,
    [DepositBSB]                   VARCHAR (20)    NULL,
    [DepositAccount]               VARCHAR (50)    NULL,
    [Overseas]                     VARCHAR (255)   NULL,
    [Country]                      VARCHAR (255)   NULL,
    [State]                        VARCHAR (255)   NULL,
    [Given_Name]                   VARCHAR (255)   NULL,
    [Surname]                      VARCHAR (255)   NULL,
    [NPLClientInd]                 VARCHAR (1)     NULL,
    [ParentGroupList]              VARCHAR (255)   NULL,
    [amountgained_last12mths]      DECIMAL (18, 2) NULL,
    [ClientSegment]                VARCHAR (100)   NULL
);

