CREATE TABLE [dbo].[tmp_marketing] (
    [First Name]        NVARCHAR (255) NULL,
    [Last Name]         NVARCHAR (255) NULL,
    [Client]            NVARCHAR (255) NULL,
    [Phone]             NVARCHAR (255) NULL,
    [Address]           NVARCHAR (255) NULL,
    [Locality]          NVARCHAR (255) NULL,
    [State]             NVARCHAR (255) NULL,
    [Postcode]          NVARCHAR (255) NULL,
    [Postal address]    NVARCHAR (255) NULL,
    [Postal Suburb]     NVARCHAR (255) NULL,
    [Postal State]      NVARCHAR (255) NULL,
    [Postal Postcode]   NVARCHAR (255) NULL,
    [Phone1]            NVARCHAR (255) NULL,
    [After hours phone] NVARCHAR (255) NULL,
    [Fax]               NVARCHAR (255) NULL,
    [Mobile]            NVARCHAR (255) NULL,
    [Main Email]        NVARCHAR (255) NULL,
    [Field1]            NVARCHAR (255) NULL,
    [Field2]            NVARCHAR (255) NULL,
    [Field3]            NVARCHAR (255) NULL,
    [Field4]            NVARCHAR (255) NULL,
    [Field5]            NVARCHAR (255) NULL,
    [Field6]            NVARCHAR (255) NULL,
    [Field7]            NVARCHAR (255) NULL
);

